name: Trigger Remote Workflow

on:
  push:
    branches:
      - qtpc

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow in VIA app repository
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.VIA_APP_TOKEN }}
          repository: QuanTrieuPCYT/via-app
          event-type: keyboard-definition-trigger
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
